[pytest]
testpaths = tests
base_url = https://practicetestautomation.com
addopts = --headed --browser chromium --screenshot on --video retain-on-failure
markers =
    smoke: Critical tests that must pass for the app to be 'up'
    regression: Full suite of tests for detailed checking

# Show logs in the terminal during execution
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s

# Capture logs for the HTML report
log_html_level = INFO

# Add this line to brand the report
addopts = --html=report.html --self-contained-html --title="PROJECT PYTHON PLAYWRIGHT - AUTOMATION HEALTH CHECK"