[pytest]
testpaths = tests
base_url = https://practicetestautomation.com
addopts = --headed --browser chromium --screenshot on --video retain-on-failure
markers =
    smoke: Critical tests that must pass for the app to be 'up'
    regression: Full suite of tests for detailed checking
