[pytest]
testpaths = tests
base_url = https://practicetestautomation.com

# Notice the quotes around the title and everything on one line

addopts = --headed --browser chromium --screenshot on --video retain-on-failure --html=report.html --self-contained-html --capture=tee-sys

markers =
    smoke: Critical tests
    regression: Full suite tests

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
# REMOVED log_html_level because it is no longer used in v4.0+


